server:
  port: 8086
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-item
    host: 127.0.0.1
    port: 3306
    pw: 123456
  swagger:
    title: "黑马商城搜索服务接口文档"
    package: com.hmall.search.controller
