server:
  port: 8080
hm:
  db:
    database: hmall
  swagger:
    title: "黑马商城服务接口文档"
    package: com.hmall.controller
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
